### PR TITLE
Support Symfony 7.1

### PR DESCRIPTION
**Pull request by rey26**
- add missing support for Symfony 7.1

### CODE REVIEW

**Comment by Prometee** [comment]
@rey26 I added the missing build tests for Symfony 7.1, lets see if everything is going well.

**Comment by Prometee** [comment]
It breaks because of a dev requirements from one of my own php package, I will add support to Sf 7 inside it and relaunch the build.

**Comment by Prometee** [comment]
I expect this to happen one day : 

```log
PHP Fatal error:  Class FluxSE\OdooApiClient\Serializer\OdooNormalizer cannot extend
final class Symfony\Component\Serializer\Normalizer\ObjectNormalizer in
src/Serializer/OdooNormalizer.php on line 15
```

It needs to be refactored, do you see how to fix this ? I build it this way because I don't wanted to copy/paste the entire Symfony `ObjectNormalizer`. Maybe now there is another way of handling it.

**Comment by Prometee** [comment]
@rey26
I tried to fix the issues but a bug in the `symfony/serializer` is triggering an error:

```
Error: Call to undefined function is_false()

vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:780
vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:380
src/Serializer/OdooNormalizer.php:35
vendor/symfony/serializer/Serializer.php:238
vendor/symfony/serializer/Normalizer/ArrayDenormalizer.php:74
vendor/symfony/serializer/Serializer.php:238
src/Manager/ModelListManager.php:56
src/Manager/ModelListManager.php:31
tests/Manager/ModelListManagerTest.php:44
```

PS: If you want to commit changes, don't forget to pull changes before.

**Comment by Prometee** [comment]
@rey26 the issue with `symfony/serializer` has been fixed but not yet merged into a stable branche nor tag yet.
And here is the related issue to `symfony/serializer` : https://github.com/symfony/symfony/issues/57334

I will merge this PR to fix #4 and then create a new major version since I remove support of symfony 5.4 packages.

**Comment by rey26** [comment]
@Prometee thanks for all of that, I was very busy these days

**Pull request merged**
